trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  name: Default
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - script: dotnet run
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Build
      env:
        AUTOMATRON_TARGETS: Build
    - script: dotnet run -- Pack -s
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Pack
