trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
variables:
- group: nuget
pool:
  vmImage: ubuntu-latest
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - script: dotnet run -- -a Version
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Version
      displayName: "\U0001F522 Version"
    - script: dotnet run -- -a Clean
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Clean
      displayName: "\U0001F9F9 Clean"
    - script: dotnet run -- -a Build
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Build
      displayName: "\U0001F3D7 Build"
    - script: dotnet run -- -a Test
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Test
      displayName: "\U0001F9EA Test"
    - script: dotnet run -- -a Pack
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Pack
      displayName: "\U0001F4E6 Pack"
    - script: dotnet run -- -a Publish
      workingDirectory: src/Automatron.Pipeline
      env:
        NUGET_API_KEY: $(NugetApiKey)
      name: Publish
      displayName: "\U0001F680 Publish"
