trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: ubuntu-latest
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - script: dotnet run -- -r Build
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Build
    - script: dotnet run -- -r Test -s
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Test
    - script: dotnet run -- -r Pack -s
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Pack
