trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  name: Default
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - task: Bash@3
      inputs:
        filePath: './run.sh'
        workingDirectory: ./src/Automatron.Pipeline
        arguments: build
      displayName: Build
    #- script: dotnet run -- Build
    #  workingDirectory: ./src/Automatron.Pipeline
    #  displayName: Build
    #- script: dotnet run -- Pack -s
    #  workingDirectory: ./src/Automatron.Pipeline
    #  displayName: Pack
