trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: ubuntu-latest
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - script: |
        dotnet build /nodeReuse:false /p:UseSharedCompilation=false -nologo -clp:NoSummary
        dotnet run --no-build -- Build
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Build
    - script: |
        dotnet build /nodeReuse:false /p:UseSharedCompilation=false -nologo -clp:NoSummary
        dotnet run --no-build --  Pack -s
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Pack
