trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: ubuntu-latest
stages:
- stage: Ci
  jobs:
  - job: Ci
    steps:
    - script: dotnet run /nodeReuse:false /p:UseSharedCompilation=false -- Build
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Build
    - script: dotnet run /nodeReuse:false /p:UseSharedCompilation=false -- Pack -s
      workingDirectory: ./src/Automatron.Pipeline
      displayName: Pack
