trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: ubuntu-latest
stages:
- stage: DeployToTesting
  jobs:
  - deployment: Deployment
    environment: Testing
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- run Ci -s DeployToTesting -j Deployment -t Init
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- run Ci -s DeployToTesting -j Deployment -t Preview
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- run Ci -s DeployToTesting -j Deployment -t Update
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
- stage: DeployToStaging
  dependsOn:
  - DeployToTesting
  jobs:
  - deployment: Deployment
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- run Ci -s DeployToStaging -j Deployment -t Init
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- run Ci -s DeployToStaging -j Deployment -t Preview
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- run Ci -s DeployToStaging -j Deployment -t Update
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
- stage: DeployToProduction
  dependsOn:
  - DeployToStaging
  jobs:
  - deployment: Deployment
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- run Ci -s DeployToProduction -j Deployment -t Init
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- run Ci -s DeployToProduction -j Deployment -t Preview
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- run Ci -s DeployToProduction -j Deployment -t Update
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
