trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: ubuntu-latest
stages:
- stage: DeployToTesting
  jobs:
  - deployment: Deployment
    environment: Testing
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0
          - task: NuGetAuthenticate@1
          - task: Pulumi@1
            displayName: Pulumi install
          - script: dotnet run -- azuredevops run --stage DeployToTesting --job Deployment --step Init -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- azuredevops run --stage DeployToTesting --job Deployment --step Preview -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- azuredevops run --stage DeployToTesting --job Deployment --step Update -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
- stage: DeployToStaging
  dependsOn:
  - DeployToTesting
  jobs:
  - deployment: Deployment
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0
          - task: NuGetAuthenticate@1
          - task: Pulumi@1
            displayName: Pulumi install
          - script: dotnet run -- azuredevops run --stage DeployToStaging --job Deployment --step Init -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- azuredevops run --stage DeployToStaging --job Deployment --step Preview -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- azuredevops run --stage DeployToStaging --job Deployment --step Update -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
- stage: DeployToProduction
  dependsOn:
  - DeployToStaging
  jobs:
  - deployment: Deployment
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0
          - task: NuGetAuthenticate@1
          - task: Pulumi@1
            displayName: Pulumi install
          - script: dotnet run -- azuredevops run --stage DeployToProduction --job Deployment --step Init -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Init
          - script: dotnet run -- azuredevops run --stage DeployToProduction --job Deployment --step Preview -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Preview
          - script: dotnet run -- azuredevops run --stage DeployToProduction --job Deployment --step Update -n Ci
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              PULUMI_API_KEY: $(PulumiApiKey)
            name: Update
