stages:
- stage: DeployToTesting
  jobs:
  - deployment: DeployToTesting
    environment: Testing
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- azuredevops run --stage "DeployToTesting" --job "DeployToTesting" --step "Version" -n "CollapsedCi"
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Version
            displayName: "\U0001F522 Version"
- stage: DeployToProduction
  jobs:
  - deployment: DeployToProduction
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- azuredevops run --stage "DeployToProduction" --job "DeployToProduction" --step "Version" -n "CollapsedCi"
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Version
            displayName: "\U0001F522 Version"
