trigger:
  batch: true
  branches:
    include:
    - master
variables:
- group: pulumi
- name: test
  value: 1
stages:
- stage: CiStage
  jobs:
  - deployment: CiJob1
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - task: Pulumi@1
            displayName: Install Pulumi
          - task: DotNetCoreCLI@2
            inputs:
              command: run
              workingDirectory: ./src/Automatron.AzureDevOps.Sample
              arguments: RunStep1
            displayName: Run Automatron
          - task: DotNetCoreCLI@2
            inputs:
              command: run
              workingDirectory: ./src/Automatron.AzureDevOps.Sample
              arguments: RunStep3
            displayName: Step 3
  - job: CiJob2
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: run
        workingDirectory: ./src/Automatron.AzureDevOps.Sample
        arguments: RunStep2
      displayName: Run Automatron
- stage: DefaultStage
  jobs:
  - job: DefaultJob
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: run
        workingDirectory: ./src/Automatron.AzureDevOps.Sample
        arguments: DefaultTask
      displayName: Run Automatron
