trigger:
  batch: true
  branches:
    include:
    - master
variables:
- group: pulumi
- name: test
  value: 1
stages:
- stage: CiStage
  jobs:
  - deployment: CiJob1
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - task: Pulumi@1
            displayName: Install Pulumi
          - script: dotnet run -- RunStep1
            workingDirectory: ./src/Automatron.AzureDevOps.Sample
            displayName: Run Automatron
          - script: dotnet run -- RunStep3
            workingDirectory: ./src/Automatron.AzureDevOps.Sample
            env:
              AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
            displayName: Step 3
  - job: CiJob2
    steps:
    - script: dotnet run -- RunStep2
      workingDirectory: ./src/Automatron.AzureDevOps.Sample
      displayName: Run Automatron
- stage: DefaultStage
  jobs:
  - job: DefaultJob
    steps:
    - script: dotnet run -- DefaultTask
      workingDirectory: ./src/Automatron.AzureDevOps.Sample
      displayName: Run Automatron
