trigger:
  batch: true
  branches:
    include:
    - main
stages:
- stage: DeployToTesting
  jobs:
  - deployment: Deployment
    pool:
      vmImage: ubuntu-latest
    environment: Name
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- -t DeploymentTestingBuild
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Build
          - script: dotnet run -- -t DeploymentTestingDeploy
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Deploy
