trigger: none
schedules:
- cron: 2 0 * * *
  displayName: Midnight
  always: false
  branches:
    include:
    - master
stages:
- stage: Integration
  jobs:
  - deployment: SetupIntegration
    timeoutInMinutes: 180
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - task: DotNetCoreCLI@2
            inputs:
              command: run
              workingDirectory: ./src/Automatron.AzureDevOps.Sample
              arguments: SetupIntegration
            displayName: Run Automatron
  - deployment: TeardownIntegration
    dependsOn:
    - SetupIntegration
    timeoutInMinutes: 180
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - task: DotNetCoreCLI@2
            inputs:
              command: run
              workingDirectory: ./src/Automatron.AzureDevOps.Sample
              arguments: TeardownIntegration
            displayName: Run Automatron
