trigger: none
schedules:
- cron: 2 0 * * *
  displayName: Midnight
  always: false
  branches:
    include:
    - master
stages:
- stage: Integration
  jobs:
  - deployment: SetupIntegration
    timeoutInMinutes: 180
    environment: InfrastructureIntegration
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - script: dotnet run -- -r SetupIntegration
            workingDirectory: ./src/Automatron.AzureDevOps.Sample
            name: SetupIntegration
  - deployment: TeardownIntegration
    dependsOn:
    - SetupIntegration
    timeoutInMinutes: 180
    environment: InfrastructureIntegration
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: NuGetAuthenticate@0
          - script: dotnet run -- -r TeardownIntegration
            workingDirectory: ./src/Automatron.AzureDevOps.Sample
            name: TeardownIntegration
