parameters:
- name: RunTests
  displayName: Run Tests
  type: string
  values:
  - Yes
  - No
trigger: none
schedules:
- cron: 2 0 * * *
  displayName: Midnight
  always: false
  branches:
    include:
    - master
variables:
- group: Nuget
- group: Pulumi
- group: Azure
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 30
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 30
pool:
  vmImage: ubuntu-latest
stages:
- stage: Integration
  variables:
  - group: Test
  - name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
    value: 60
  - name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
    value: 60
  jobs:
  - deployment: Setup
    environment: Integration
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- run --stage Integration --job Setup --step Init Int
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              RUN_TESTS: ${{ parameters.RunTests }}
              NUGET_API_KEY: $(NugetApiKey)
              AZURE_CLIENT_ID: $(AzureClientId)
            name: Init
          - script: dotnet run -- run --stage Integration --job Setup --step Update Int
            workingDirectory: src/Automatron.AzureDevOps.Sample
            env:
              RUN_TESTS: ${{ parameters.RunTests }}
              NUGET_API_KEY: $(NugetApiKey)
              AZURE_CLIENT_ID: $(AzureClientId)
            name: Update
  - deployment: Teardown
    dependsOn:
    - Setup
    environment: Integration
    strategy:
      runOnce:
        deploy:
          steps:
          - script: dotnet run -- run --stage Integration --job Teardown --step Init Int
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Init
          - script: dotnet run -- run --stage Integration --job Teardown --step Destroy Int
            workingDirectory: src/Automatron.AzureDevOps.Sample
            name: Destroy
