trigger: none
stages:
- stage: PrStage
  jobs:
  - job: PrJob
    steps:
    - script: dotnet run -- PrTask
      workingDirectory: ./src/Automatron.AzureDevOps.Sample
      displayName: Run Automatron
